package com.nhutruong.blood.audit.domain;

public enum AuditAction {
    CREATE,
    UPDATE,
    DELETE,
    APPROVE,
    REJECT,
    RESERVE,
    RELEASE,
    DISPATCH,
    DELIVER,
    LOGIN,
    LOGOUT,
    EXPORT,
    EMERGENCY_ALERT,
    ORGANIZATION_VERIFIED,
    ORGANIZATION_REJECTED,
    ORGANIZATION_SUSPENDED,
    ORGANIZATION_MEMBER_ADDED,
    ORGANIZATION_MEMBER_REMOVED,
    INVENTORY_RESERVED,
    INVENTORY_RELEASED}
