## H2 DB connection for local testing without Docker
spring.datasource.url=jdbc:h2:mem:blooddb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true

spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data-local.sql

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

## Flyway Migration settings
spring.flyway.enabled=false

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.probes.enabled=true
