INSERT INTO users (
    id,
    created_at,
    updated_at,
    version,
    email,
    password,
    first_name,
    last_name,
    blood_group,
    role,
    status
) VALUES
    (
        1001,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP,
        0,
        'choray.center@example.com',
        '$2a$10$7EqJtq98hPqEX7fNZaFWoOQzUoF0xhVuAAjyZHG2jN7j8iZmJmC2e',
        'Cho Ray',
        'Medical Center',
        NULL,
        'MEDICALCENTER',
        'ACTIVE'
    ),
    (
        1002,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP,
        0,
        'huyethoc.center@example.com',
        '$2a$10$7EqJtq98hPqEX7fNZaFWoOQzUoF0xhVuAAjyZHG2jN7j8iZmJmC2e',
        'Huyet Hoc',
        'Medical Center',
        NULL,
        'MEDICALCENTER',
        'ACTIVE'
    ),
    (
        1003,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP,
        0,
        'quan7.center@example.com',
        '$2a$10$7EqJtq98hPqEX7fNZaFWoOQzUoF0xhVuAAjyZHG2jN7j8iZmJmC2e',
        'Quan 7',
        'Medical Center',
        NULL,
        'MEDICALCENTER',
        'ACTIVE'
    ),
    (
        1004,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP,
        0,
        'bachmai.center@example.com',
        '$2a$10$7EqJtq98hPqEX7fNZaFWoOQzUoF0xhVuAAjyZHG2jN7j8iZmJmC2e',
        'Bach Mai',
        'Medical Center',
        NULL,
        'MEDICALCENTER',
        'ACTIVE'
    ),
    (
        1005,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP,
        0,
        'hanoi.blood.center@example.com',
        '$2a$10$7EqJtq98hPqEX7fNZaFWoOQzUoF0xhVuAAjyZHG2jN7j8iZmJmC2e',
        'Ha Noi',
        'Blood Center',
        NULL,
        'MEDICALCENTER',
        'ACTIVE'
    );

INSERT INTO donation_location (
    id,
    name,
    address,
    latitude,
    longitude,
    slug,
    seo_title,
    seo_description,
    published,
    created_by_id,
    created_at,
    updated_at
) VALUES
    (
        2001,
        'Benh vien Cho Ray',
        '201B Nguyen Chi Thanh, Phuong 12, Quan 5, TP.HCM',
        10.7579,
        106.6602,
        'benh-vien-cho-ray',
        'Benh vien Cho Ray - Diem hien mau',
        'Trung tam tiep nhan hien mau tai Benh vien Cho Ray.',
        TRUE,
        1001,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        2002,
        'Benh vien Truyen mau Huyet hoc',
        '118 Hong Bang, Phuong 12, Quan 5, TP.HCM',
        10.7547,
        106.6674,
        'benh-vien-truyen-mau-huyet-hoc',
        'Benh vien Truyen mau Huyet hoc - Diem hien mau',
        'Diem tiep nhan hien mau co dinh tai TP.HCM.',
        TRUE,
        1002,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        2003,
        'Diem hien mau Quan 7',
        '101 Nguyen Thi Thap, Quan 7, TP.HCM',
        10.7411,
        106.7131,
        'diem-hien-mau-quan-7',
        'Diem hien mau Quan 7',
        'Diem hien mau cong dong tai Quan 7.',
        TRUE,
        1003,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        2004,
        'Benh vien Bach Mai',
        '78 Giai Phong, Phuong Phuong Mai, Quan Dong Da, Ha Noi',
        21.0014,
        105.8410,
        'benh-vien-bach-mai',
        'Benh vien Bach Mai - Diem hien mau',
        'Diem tiep nhan hien mau tai Benh vien Bach Mai, Ha Noi.',
        TRUE,
        1004,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        2005,
        'Vien Huyet hoc Truyen mau Trung uong',
        'Pham Van Bach, Phuong Yen Hoa, Quan Cau Giay, Ha Noi',
        21.0291,
        105.7852,
        'vien-huyet-hoc-truyen-mau-trung-uong',
        'Vien Huyet hoc Truyen mau Trung uong',
        'Diem tiep nhan hien mau lon tai Ha Noi.',
        TRUE,
        1005,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    );

INSERT INTO donation_schedule (id, donation_time, capacity, location_id) VALUES
    (3001, DATEADD('DAY', 1, CURRENT_TIMESTAMP), 80, 2001),
    (3002, DATEADD('DAY', 3, CURRENT_TIMESTAMP), 120, 2001),
    (3003, DATEADD('DAY', 2, CURRENT_TIMESTAMP), 100, 2002),
    (3004, DATEADD('DAY', 4, CURRENT_TIMESTAMP), 60, 2003),
    (3005, DATEADD('DAY', 1, CURRENT_TIMESTAMP), 90, 2004),
    (3006, DATEADD('DAY', 2, CURRENT_TIMESTAMP), 140, 2005);

INSERT INTO user_profiles (
    id,
    user_id,
    phone,
    birth_date,
    gender,
    address,
    latitude,
    longitude,
    emergency_alert_opt_in,
    last_donation_date,
    next_eligible_date,
    created_at,
    updated_at
) VALUES
    (
        4001,
        1001,
        '02838221234',
        NULL,
        'UNSPECIFIED',
        '201B Nguyen Chi Thanh, Quan 5, TP.HCM',
        10.7579,
        106.6602,
        FALSE,
        NULL,
        NULL,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        4002,
        1002,
        '02839557858',
        NULL,
        'UNSPECIFIED',
        '118 Hong Bang, Quan 5, TP.HCM',
        10.7547,
        106.6674,
        FALSE,
        NULL,
        NULL,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        4003,
        1003,
        '02837711111',
        NULL,
        'UNSPECIFIED',
        '101 Nguyen Thi Thap, Quan 7, TP.HCM',
        10.7411,
        106.7131,
        FALSE,
        NULL,
        NULL,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        4004,
        1004,
        '02438693731',
        NULL,
        'UNSPECIFIED',
        '78 Giai Phong, Dong Da, Ha Noi',
        21.0014,
        105.8410,
        FALSE,
        NULL,
        NULL,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        4005,
        1005,
        '02437821898',
        NULL,
        'UNSPECIFIED',
        'Pham Van Bach, Cau Giay, Ha Noi',
        21.0291,
        105.7852,
        FALSE,
        NULL,
        NULL,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    );
